[icedos.desktop.hyprland.settings]
followMouse = 1 # Options: https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor
secondsToLowerBrightness = 60
startupScript = ""
windowRules = []

[icedos.desktop.hyprland.settings.animations]
enable = true
bezierCurve = "0.83, 0, 0.17, 1" # Presets: https://easings.net
speed = 2 # Function: (x * 100)ms

[icedos.desktop.hyprland.plugins]
hyprspace = false

[icedos.desktop.hyprland.plugins.cs2fix]
enable = false
width = 0
height = 0

[icedos.desktop.hyprland.plugins.hyproled]
enable = false
startWidth = 0
startHeight = 0
endWidth = 0
endHeight = 0
